[package]
name = "nano-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
js-sys = "0.3.64"
log = "0.4.20"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.37"
wee_alloc = "0.4.5"

[dependencies.web-sys]
version = "0.3.64"
features = [
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Window',
]

# https://rustwasm.github.io/wasm-pack/book/cargo-toml-configuration.html
[package.metadata.wasm-pack.profile.profiling]
wasm-opt = [ "-Oz", "--dce", "-g" ] # "-g"

[profile.release]
lto = true
opt-level = 'z'
panic = 'abort'