[build]
rustflags = [
#    "-C", "target-feature=+atomics,+bulk-memory,+exception-handling,+multivalue,+mutable-globals,+nontrapping-fptoint,+reference-types,+sign-ext,+simd128,+crt-static",
]

[unstable]
build-std = ["panic_abort", "core", "std", "alloc", "proc_macro"]
